server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**, /api/product/**, /products/**, /product/**
        - id: category-service
          uri: lb://category-service
          predicates:
            - Path=/api/categories/**, /api/category/**, /categories/**, /category/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/